@extends('layouts.app')
@section('title', 'Temukan Partner — SkillMate')
@section('content')
<div class="sm-page">
    <section class="sm-workspace-hero mb-7"><div class="relative z-10"><p class="sm-eyebrow">KOMUNITAS SKILLMATE</p><h1 class="mt-2 text-3xl font-extrabold tracking-tight">Temukan partner yang sejalan</h1><p class="mt-2 max-w-xl text-sm leading-6 text-blue-100/80">Jelajahi pembelajar berdasarkan keahlian dan tujuan yang ingin kamu capai bersama.</p></div></section>
    <section class="sm-card mb-7"><div class="border-b border-slate-100 px-6 py-4"><h2 class="font-bold text-slate-900">Cari dengan preferensimu</h2><p class="mt-1 text-sm text-muted">Gunakan filter untuk menemukan koneksi yang lebih relevan.</p></div><div class="sm-card-body"><form action="{{ route('partners.index') }}" method="GET" class="grid grid-cols-1 items-end gap-4 md:grid-cols-12"><div class="md:col-span-5"><label for="skill" class="sm-label">Keahlian</label><select name="skill" id="skill" class="sm-select"><option value="">Semua skill</option>@foreach($skills as $skill)<option value="{{ $skill->name }}" @selected(old('skill', $selectedSkill) === $skill->name)>{{ $skill->name }}</option>@endforeach</select></div><div class="md:col-span-4"><label for="type" class="sm-label">Tujuan partner</label><select name="type" id="type" class="sm-select"><option value="" @selected(old('type', $selectedType) === null || old('type', $selectedType) === '')>Semua tujuan</option><option value="offering" @selected(old('type', $selectedType) === 'offering')>Bisa mengajarkan</option><option value="learning" @selected(old('type', $selectedType) === 'learning')>Ingin belajar</option></select></div><div class="flex gap-2 md:col-span-3"><button type="submit" class="sm-btn-primary flex-1">Cari partner</button><a href="{{ route('partners.index') }}" class="sm-btn-secondary">Reset</a></div></form></div></section>
    <div class="mb-4 flex items-end justify-between"><div><p class="sm-eyebrow">HASIL PENCARIAN</p><h2 class="mt-1 text-xl font-bold text-slate-900">Partner untukmu <span class="font-normal text-muted">({{ $partners->count() }})</span></h2></div></div>
    <div class="grid grid-cols-1 gap-4 lg:grid-cols-2">@forelse($partners as $partner) @php($initials = collect(explode(' ', $partner->name))->filter()->take(2)->map(fn ($w) => strtoupper(substr($w, 0, 1)))->implode(''))<article class="sm-card group"><div class="sm-card-body p-6"><div class="flex gap-4"><span class="sm-avatar-lg ring-primary-50">{{ $initials }}</span><div class="min-w-0 flex-1"><div class="flex flex-wrap items-start justify-between gap-2"><div><h3 class="text-lg font-bold text-slate-900">{{ $partner->name }}</h3>@if($partner->profile)<p class="mt-1 text-sm text-muted">{{ $partner->profile->school }} · {{ $partner->profile->major }}</p>@endif</div>@if($partner->is_match)<span class="sm-badge-match">✦ Skill match</span>@endif</div>@if($partner->profile?->bio)<p class="mt-3 line-clamp-2 text-sm leading-6 text-slate-600">{{ $partner->profile->bio }}</p>@endif</div></div><div class="mt-5 space-y-3 border-t border-slate-100 pt-4"><div class="flex flex-wrap gap-2"><span class="w-full text-[11px] font-bold uppercase tracking-wider text-muted">Bisa mengajarkan</span>@forelse($partner->offering_skills as $userSkill)<span class="sm-badge-success">{{ $userSkill->skill->name }}</span>@empty<span class="text-sm text-muted">Belum ditambahkan</span>@endforelse</div><div class="flex flex-wrap gap-2"><span class="w-full text-[11px] font-bold uppercase tracking-wider text-muted">Ingin belajar</span>@forelse($partner->learning_skills as $userSkill)<span class="sm-badge-info">{{ $userSkill->skill->name }}</span>@empty<span class="text-sm text-muted">Belum ditambahkan</span>@endforelse</div></div><a href="{{ route('partners.show', $partner) }}" class="sm-btn-secondary mt-5 w-full">Lihat profil partner <span>→</span></a></div></article>@empty <div class="sm-card col-span-full"><div class="sm-empty py-16"><div class="mx-auto mb-4 grid h-14 w-14 place-items-center rounded-2xl bg-primary-50 text-2xl text-primary">⌕</div><p class="sm-empty-title">Belum menemukan partner yang cocok</p><p class="sm-empty-text">Coba ganti filter atau lengkapi skill agar rekomendasi lebih akurat.</p><a href="{{ route('user.skills.index') }}" class="sm-btn-primary mt-5">Lengkapi skill saya</a></div></div>@endforelse</div>
</div>
@endsection
