@extends('layouts.app')

@section('title', 'Dashboard — SkillMate')

@section('content')
<div class="sm-page">
    <section class="relative mb-8 overflow-hidden rounded-3xl bg-[#102a56] px-6 py-8 text-white shadow-[0_18px_40px_rgb(16_42_86_/_18%)] sm:px-9 sm:py-10">
        <div class="absolute -right-12 -top-20 h-64 w-64 rounded-full border border-white/10"></div><div class="absolute right-24 -bottom-28 h-56 w-56 rounded-full border border-white/10"></div>
        <div class="relative flex flex-col gap-6 lg:flex-row lg:items-end lg:justify-between"><div><span class="inline-flex rounded-full bg-white/10 px-3 py-1 text-xs font-bold tracking-wide text-blue-100">DASHBOARD PRIBADI</span><h1 class="mt-4 text-3xl font-extrabold tracking-tight sm:text-4xl">Halo, {{ auth()->user()->name }}! ✦</h1><p class="mt-2 max-w-xl text-sm leading-6 text-blue-100/80 sm:text-base">Langkah kecil yang kamu lakukan hari ini membawa kamu lebih dekat ke tujuan belajar.</p></div><a href="{{ route('partners.index') }}" class="inline-flex shrink-0 items-center justify-center gap-2 rounded-xl bg-white px-4 py-3 text-sm font-bold text-primary shadow-lg transition hover:-translate-y-0.5">Temukan partner <span>→</span></a></div>
    </section>

    <div class="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-4">
        <div class="sm-stat-card"><div class="mb-4 flex h-10 w-10 items-center justify-center rounded-xl bg-primary-50 text-primary"><svg class="h-5 w-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z"/></svg></div><div class="sm-stat-value">{{ $totalSkills }}</div><div class="sm-stat-label">Total skill saya</div></div>
        <div class="sm-stat-card"><div class="mb-4 flex h-10 w-10 items-center justify-center rounded-xl bg-success-light text-success">↑</div><div class="sm-stat-value text-success">{{ $offeringCount }}</div><div class="sm-stat-label">Siap saya ajarkan</div></div>
        <div class="sm-stat-card"><div class="mb-4 flex h-10 w-10 items-center justify-center rounded-xl bg-info-light text-info">◎</div><div class="sm-stat-value text-info">{{ $learningCount }}</div><div class="sm-stat-label">Sedang ingin dipelajari</div></div>
        <div class="sm-stat-card"><div class="mb-4 flex h-10 w-10 items-center justify-center rounded-xl bg-warning-light text-warning">✦</div><div class="sm-stat-value text-primary">{{ $learningRequestCount }}</div><div class="sm-stat-label">Koneksi belajar</div></div>
    </div>

    <div class="mt-8 grid grid-cols-1 gap-5 lg:grid-cols-3"><section class="sm-card lg:col-span-2"><div class="sm-card-body p-6 sm:p-7"><span class="text-xs font-bold tracking-wider text-primary">LANGKAH BERIKUTNYA</span><h2 class="mt-2 text-xl font-bold text-slate-900">Lengkapi ruang belajarmu</h2><p class="mt-2 max-w-lg text-sm leading-6 text-muted">Tambahkan skill yang kamu kuasai atau pelajari agar rekomendasi partner semakin tepat.</p><div class="mt-5 flex flex-wrap gap-3"><a href="{{ route('user.skills.index') }}" class="sm-btn-primary">Kelola skill saya</a><a href="{{ route('partners.index') }}" class="sm-btn-secondary">Jelajahi partner</a></div></div></section><aside class="rounded-2xl border border-blue-100 bg-primary-50 p-6"><p class="text-sm font-bold text-primary-700">Tips hari ini</p><p class="mt-3 text-sm leading-6 text-slate-600">Partner terbaik bukan yang paling hebat, tetapi yang punya tujuan dan ritme belajar yang sejalan.</p></aside></div>

    <section class="mt-8"><div class="mb-4 flex items-center justify-between"><div><h2 class="text-lg font-bold text-slate-900">Akses cepat</h2><p class="mt-1 text-sm text-muted">Kelola semua aktivitasmu dari sini.</p></div></div><div class="grid grid-cols-1 gap-4 sm:grid-cols-3"><a href="{{ route('user.skills.index') }}" class="sm-card group p-5 transition hover:-translate-y-1 hover:shadow-card"><span class="mb-4 flex h-10 w-10 items-center justify-center rounded-xl bg-primary-50 text-primary group-hover:bg-primary group-hover:text-white transition">✦</span><h3 class="font-bold text-slate-900">Kelola skill</h3><p class="mt-1 text-sm text-muted">Tambah dan atur tujuan belajarmu.</p></a><a href="{{ route('partners.index') }}" class="sm-card group p-5 transition hover:-translate-y-1 hover:shadow-card"><span class="mb-4 flex h-10 w-10 items-center justify-center rounded-xl bg-info-light text-info group-hover:bg-info group-hover:text-white transition">◎</span><h3 class="font-bold text-slate-900">Temukan partner</h3><p class="mt-1 text-sm text-muted">Cari teman dengan skill yang tepat.</p></a><a href="{{ route('learning-requests.index') }}" class="sm-card group p-5 transition hover:-translate-y-1 hover:shadow-card"><span class="mb-4 flex h-10 w-10 items-center justify-center rounded-xl bg-success-light text-success group-hover:bg-success group-hover:text-white transition">↗</span><h3 class="font-bold text-slate-900">Learning request</h3><p class="mt-1 text-sm text-muted">Lihat koneksi dan request belajarmu.</p></a></div></section>
</div>
@endsection
