@extends('layouts.app')
@section('title', 'Skill Saya — SkillMate')
@section('content')
<div class="sm-page">
    <section class="sm-workspace-hero mb-7"><div class="relative z-10 flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><p class="sm-eyebrow">PROFIL PEMBELAJAR</p><h1 class="mt-2 text-3xl font-extrabold tracking-tight">Peta skill kamu</h1><p class="mt-2 max-w-xl text-sm leading-6 text-blue-100/80">Tunjukkan apa yang bisa kamu bagikan dan tentukan hal baru yang ingin kamu kuasai.</p></div><div class="rounded-2xl border border-white/10 bg-white/10 px-4 py-3"><b class="block text-xl">{{ $userSkills->count() }}</b><span class="text-xs text-blue-100/75">skill dalam profil</span></div></div></section>
    @if(session('success'))<div class="sm-alert-success">{{ session('success') }}</div>@endif
    @if($errors->any())<div class="sm-alert-danger"><ul class="list-disc list-inside space-y-1">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
    <div class="grid grid-cols-1 gap-6 lg:grid-cols-5">
        <section class="sm-card h-fit lg:col-span-2"><div class="sm-card-body p-6"><p class="sm-eyebrow">TAMBAHKAN KEAHLIAN</p><h2 class="mt-2 text-xl font-bold">Apa targetmu berikutnya?</h2><p class="mt-2 text-sm leading-6 text-muted">Pilih skill dan tentukan peranmu agar partner yang direkomendasikan makin relevan.</p><form action="{{ route('user.skills.store') }}" method="POST" class="mt-6 space-y-5">@csrf<div><label for="skill_id" class="sm-label">Pilih skill</label><select name="skill_id" id="skill_id" class="sm-select" required><option value="">Cari dari daftar skill...</option>@foreach($skills as $skill)<option value="{{ $skill->id }}" @selected(old('skill_id') == $skill->id)>{{ $skill->name }}@if($skill->category) — {{ $skill->category->name }}@endif</option>@endforeach</select></div><div><span class="sm-label">Saya ingin...</span><div class="flex flex-col gap-2"><label class="sm-option"><input type="radio" name="type" value="offering" @checked(old('type') === 'offering') required><span><b class="block">Mengajarkan</b><small class="font-normal text-muted">Berbagi keahlian dengan partner</small></span></label><label class="sm-option"><input type="radio" name="type" value="learning" @checked(old('type') === 'learning')><span><b class="block">Mempelajari</b><small class="font-normal text-muted">Belajar dari partner komunitas</small></span></label></div></div><button type="submit" class="sm-btn-primary w-full">+ Tambahkan ke profil</button></form></div></section>
        <section class="sm-card lg:col-span-3"><div class="sm-card-header flex items-center justify-between"><div><h2 class="sm-card-title">Koleksi skill</h2><p class="mt-1 text-sm text-muted">Keahlian yang membentuk profilmu.</p></div><span class="sm-badge-primary">{{ $userSkills->count() }} total</span></div><div class="sm-card-body p-4 sm:p-5">@forelse($userSkills as $userSkill)<article class="group flex flex-col gap-4 rounded-2xl border border-slate-100 p-4 transition hover:border-primary-100 hover:bg-primary-50/30 sm:flex-row sm:items-center sm:justify-between"><div class="flex items-center gap-4"><span class="flex h-11 w-11 items-center justify-center rounded-xl bg-primary-50 font-display font-extrabold text-primary">{{ strtoupper(substr($userSkill->skill->name, 0, 1)) }}</span><div><h3 class="font-bold text-slate-900">{{ $userSkill->skill->name }}</h3>@if($userSkill->skill->category)<p class="mt-0.5 text-sm text-muted">{{ $userSkill->skill->category->name }}</p>@endif</div></div><div class="flex items-center justify-between gap-3 sm:justify-end">@if($userSkill->type === 'offering')<span class="sm-badge-success">Siap mengajarkan</span>@else<span class="sm-badge-info">Sedang dipelajari</span>@endif<form action="{{ route('user.skills.destroy', $userSkill->id) }}" method="POST">@csrf @method('DELETE')<button type="submit" class="rounded-lg p-2 text-slate-400 transition hover:bg-danger-light hover:text-danger" onclick="return confirm('Hapus skill ini?')" aria-label="Hapus skill">×</button></form></div></article>@empty<div class="sm-empty py-16"><div class="mx-auto mb-4 grid h-14 w-14 place-items-center rounded-2xl bg-primary-50 text-2xl text-primary">✦</div><p class="sm-empty-title">Profilmu siap untuk diisi</p><p class="sm-empty-text">Mulai dari satu skill yang ingin kamu ajarkan atau pelajari.</p></div>@endforelse</div></section>
    </div>
</div>
@endsection
